FROM node:12
WORKDIR /app
RUN npm install -g ganache-cli
EXPOSE 8545
CMD ["ganache-cli" , "-m",  "speak card review photo quote endless alpha metal long reflect angle rare", "-l", "6800000", "-g", "65164000", "-h", "0.0.0.0" ]